  macos:
    name: Create artifacts on macOS
    runs-on: macos-11
    steps:
      - name: Preparations
        env:
          MACOS_CERT: ${{ secrets.MACOS_CERT }}
          MACOS_CERT_PWD: ${{ secrets.MACOS_CERT_PWD }}
        run: |
          echo $MACOS_CERT | base64 --decode > macos_cert.p12
          security create-keychain -p buildchain build.chain
          security default-keychain -s build.chain
          security unlock-keychain -p buildchain build.chain
          security set-keychain-settings build.chain
          security import macos_cert.p12 -k build.chain -P $MACOS_CERT_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k buildchain build.chain
          rm -f macos_cert.p12
          # actions/setup-java@v2 removes the directories MacOS and _CodeSignature and the file Info.plist from the JDK, so we cannot use it for the application
          wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jdk_x64_mac_hotspot_17.0.5_8.tar.gz
          tar zxf OpenJDK17U-jdk_x64_mac_hotspot_17.0.5_8.tar.gz -C $RUNNER_TEMP
          echo "JAVA_HOME=$RUNNER_TEMP/jdk-17.0.5+8/Contents/Home" >> $GITHUB_ENV
          echo "$RUNNER_TEMP/jdk-17.0.5+8/Contents/Home/bin" >> $GITHUB_PATH
          # install tools for DMG creation:
          npm install --global create-dmg
          brew install graphicsmagick imagemagick
      - name: Disable automatic EOL conversions
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew dmg
        working-directory: kse
      - name: Store artifacts for release
        uses: actions/upload-artifact@v2
        with:
          name: macos-artifact
          path: kse/build/distributions/kse*.dmg

  release:
